### ISSUE TITLE
[Wallet] Wallet sync fails

### ISSUE THREAD

**Issue by pawelgrzybek** [EYBlockchain/nightfall_3#1127]
**Describe the bug**

Currently the wallet sync fails.

**Expected behavior**

To successfully sync.

**To Reproduce**

`npm run start` or `npm run start:testnet`

**Browser (if applicable):**
- Firefox
- Chrome
- Safari
- Microsoft Edge
- Others

**Comment by druiz0992** [comment]
One of the reasons it is failing is because the file containing the hashes, `s3_hashes.txt` is empty. This file is generated in `entrypoint.sh` inside hosted-utils-api-server.

Lines 19-27

```    
skip=1
    if [ "${USE_STUBS}" = 'true' ] && [[ "${PROVING_FILE_FOLDERS}" == *"_stub" ]]; then 
      skip=0
    elif [ "${USE_STUBS}" = 'false' ] && [[ "${PROVING_FILE_FOLDERS}" != *"_stub" ]]; then
      skip=0
    fi
    if [ "${skip}" = "1" ]; then
      continue
    fi
```
Problem is that `${USE_STUBS}` may not be defined. In this case, we should assume its false. So, this code should be changed to:
```    
skip=1
    if [ "${USE_STUBS}" = 'true' ] && [[ "${PROVING_FILE_FOLDERS}" == *"_stub" ]]; then 
      skip=0
    elif [[ "${PROVING_FILE_FOLDERS}" != *"_stub" ]]; then
      skip=0
    fi
    if [ "${skip}" = "1" ]; then
      continue
    fi
```

**Comment by pawelgrzybek** [comment]
Thank you for your help @druiz0992
