### ISSUE TITLE
X509 

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#1234]
X509 required activities
- [x] Assign good certificase to some users
- [x] Assign bad certificates to some users
- [x] Add final CA roots
- [ ] Other...

**Comment by israelboudoux** [comment]
I have created a script for creating the certificates - it creates the Root CA certificate and the X users' certificates. The certificates are being generated correctly with the expected flags, but when I tried to test them using the X509 Unit Test, it fails for the test _**'Should validate the user certificate'**_, while passes the other two tests - this is a modified version for the X509 unit test that I changed because I'm not generating an intermediate CA (branch: israelboudoux/test-x509). The error is the following: 

```
     Error: VM Exception while processing transaction: reverted with reason string 'X509: Decrypt does not have a leading zero octets'
      at X509.onlyOwner (nightfall-deployer/contracts/Ownable.sol:26)
      at X509.validateSignatureAndExtractMessageHash (nightfall-deployer/contracts/X509.sol:91)
      at X509.checkSignature (nightfall-deployer/contracts/X509.sol:268)
      at X509.validateCertificate (nightfall-deployer/contracts/X509.sol:300)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The point is that when I comment out the following two `require` validation [here](https://github.com/EYBlockchain/nightfall_3/blob/master/nightfall-deployer/contracts/X509.sol#L97) the test passes successfully. I understand that some parameters are expected after decrypting the signature, but I don't what to do for these parameters comply with the expected validations in the X509 contract. 

Follows the certificate + priv_key attached that I used for testing, but the code for generating it can be seeing in the PR at [https://github.com/EYBlockchain/nightfall_3_private/pull/313](https://github.com/EYBlockchain/nightfall_3_private/pull/313).

**Comment by israelboudoux** [comment]
Hey @Westlad, would you mind adding the flags you used to create each of the certs (CA & end-user)? Maybe I'm missing some of them.

Thanks!

**Comment by Westlad** [comment]
Hi @israelboudoux.  For current Master they are:
For a CA - key usage flag: Certificate Sign, CRL Sign
For an end user cert: Digital Signature, Non repudiation .
Once #1259 is merged, you will also need:
Extended Key Usage must be whatever you tell X509.sol to use when you deploy (must be something).  The test uses: Code Signing, E-mail Protection, Time Stamping (probably not what we would use in a real deploy).
Certificate Policies must be whatever you tell X509.sol to use when you deploy (must be something). The test uses OIDs 1.2.3.4 and 1.5.6.7.
There is no longer a Non-Repudiation check for key usage.

**Comment by Westlad** [comment]
It looks like the digital signature check is failing for you though, rather than one of the certificate properties not being correct. Make sure you are using RSA (2048 bit is tested but it should be good for any key length) and not EC crypto.

**Comment by israelboudoux** [comment]
Hi @Westlad, the certs are RSA ones using 4096 bits for the key. The signature check passes if I comment out the two require validations in `validateSignatureAndExtractMessageHash`. I'll check if the root certificate has the flag `CRL Sign`.

Would you know which RFC can I check to verify the OIDs 1.2.3.4 and 1.5.6.7?

**Comment by Westlad** [comment]
> Would you know which RFC can I check to verify what the OIDs 1.2.3.4 and 1.5.6.7 are about?
I just made those up.  Certificate Policies are unique to the CA and they pick their own OIDs.  Policies are supposed to be specified in their Certificate Practice Statement but actually they don't often seem to state which OID goes with which policy, which makes things harder than they should be; takes a bit of detective work to associate an OID with a policy.

**Comment by israelboudoux** [comment]
The work is done in the PR: https://github.com/EYBlockchain/nightfall_3_private/pull/313
