### ISSUE TITLE
Implement knowledge of signature for public inputs for good practice against malleability 

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#298]
The results from this paper https://eprint.iacr.org/2020/811.pdf means that because an adversary should not be able to mess with the public input and malleability should not exist. To be on the safe side and follow good practices, it is recommended to prove knowledge of a signature on the public inputs inside the SNARK. This shouldn't add too much overhead and it also shouldn't interfere with privacy because the signature is never revealed in the clear. 
Thanking Mary Maller for her insight her.

**Comment by MirandaWood** [comment]
After some discussion, it seems like a signature entirely within the snark would not provide any protection against the malleability for our use case. While adding a signature of the proof with the signing public key as part of the public inputs _would_ work, that would add storage overhead to each tx object. Plus we already protect against the malleability for transfer and withdraw, since those will trigger nullifier challenges.
However, for deposit transactions it is currently possible for an attacker to create a new different proof based on somebody else's proof. They could create a new tx with all the same params but a different proof, making the innocent depositor pay twice. 
Considering that deposits are pre-paid, is it possible for an innocent user to be forced to deposit twice? If so, as Ilyas suggested, should we add a duplicate commitment challenge?

**Comment by MirandaWood** [comment]
> is it possible for an innocent user to be forced to deposit twice?

No - when `submitTransaction` is called, the `msg.sender` pays in the amount deposited. So an attacker can create a tx with identical info apart from the proof, submit it, and pay in _their own_ tokens. The current system will see no issue with this second tx (since it's not a duplicate, and the proof verifies). 
However the attacker can't do anything malicious with it. They will have an identical commitment to the original user, but cannot spend it. Whenever the original user spends it, the attacker can either front-run that tx (and pay fees for them) or submit it afterwards, which will fail with a duplicate nullifier (locking the attacker's funds in the contract).
So...
> should we add a duplicate commitment challenge?

Though it feels off to have two identical commitments in the MT, the attacker does not know the salt and so cannot claim the funds for themselves. I don't believe they can do anything malicious with it. 
If we did add a duplicate commitment challenge, an attacker could front-run a deposit tx, make the innocent user's tx an invalid duplicate and prevent them from depositing. But that means the attacker's funds would be locked in the shield, unless the innocent user goes rogue and decides to take it for themselves.
