### ISSUE TITLE
Changing current proposer in Ropsten is not working.

### ISSUE THREAD

**Issue by daveroga** [EYBlockchain/nightfall_3#307]
Doing tests in Ropsten I got some errors:

- It seems when a proposer stops working and is the current proposer (thisAddress), then there won't be any proposers proposing blocks because new proposers get always "Fail with error 'Only the current proposer can call this.'". It seems currentProposer is still the old proposer and is not changing to new registered ones, so new blocks are not being proposed.
I've opened an issue #309 about adding changeCurrentProposer in the SDK calling `/proposer/change` endpoint.

- Getting `The block is out of order` when the proposer tries to propose a block.
I use different keys for user and proposer, so it seems it's not something related with nonce, but I'm investigating it.

I provide some information about the tests in order to figure out what could be the cause.

- Proposer address: 0x0d234bb221c5f608261e9a1b6edef6e5a10d8bf6. https://ropsten.etherscan.io/address/0x0d234bb221c5f608261e9a1b6edef6e5a10d8bf6
- State contract address: 0x69955D34691d8D805543853566a3266E3143aEb0.  https://ropsten.etherscan.io/address/0x69955D34691d8D805543853566a3266E3143aEb0
- Proposers contract address: 0x828c60A00aa95c280d7b3dC5E879006D387bdA2f
https://ropsten.etherscan.io/address/0x828c60A00aa95c280d7b3dC5E879006D387bdA2f

I've upload branch `daveroga/refactoring-test-files` with the test I'm running. Now working in an issue related with `changeCurrentProposer` that seems is not working.

To run the test pull the branch and `npm run test-e2e-ropsten` that is the same test as `npm run test-e2e` but with the environment in Ropsten and testing directly to the services running in AWS.

**Comment by IlyasRidhuan** [comment]
Hm is this happening when `deRegisterProposer` is called by the current proposer? This removes a proposer from the list of proposers.

There is an edge-case there where we might need to rotate the proposer in this function if the `currentProposer` is the one that de-registers. Otherwise, we will have to wait out the `ROTATE_PROPOSER_BLOCKS` time before someone else can call `changeCurrentProposer`.

**Comment by daveroga** [comment]
I was testing the `changeCurrentProposer` functionality I added to SDK that calls the `/proposer/change` endpoint.

**Comment by daveroga** [comment]
When testing also the SDK with `getProposers` that is calling the endpoint `proposer/proposers` I think is something wrong in the loop as I always I'm getting 1 proposer en the collection.

I think `thisPtr` could be assigned to `proposer.previousAddress` for instance as showing in the change I propose?

![image](https://user-images.githubusercontent.com/70919589/142637476-0ea2be29-6822-443d-ad60-33a814900215.png)

**Comment by IlyasRidhuan** [comment]
Yeah you are right, that does look like a bug. As a thought, you might want to use `proposer.nextAddress` instead of `previousAddress`. That way the `/proposers` array will be the in the order of upcoming proposers - rather than having to reverse the list.

This may be useful if you are a proposer and trying to estimate when you will be the next proposer.

**Comment by daveroga** [comment]
Yeah. Using `proposer.nextAddress` was my first thought, but as you see in the image above, it seems there is some bug also in `nextAddress` recalculation when new proposers register, as in this case `nextAddress` is the same  address for both proposers and as you mention it should be cyclical and allows to go to all the proposers by navigating through this property.
