### ISSUE TITLE
Fix proposers collection and endpoint

### ISSUE THREAD

**Issue by daveroga** [EYBlockchain/nightfall_3#313]
Now it seems `proposer/proposers` endpoint is not returning all the proposers in the proposers collection. Also it seems `nextAddress` is not working as expecting allowing to cycling navigate to all proposers.

**Comment by IlyasRidhuan** [comment]
Following up on [this](https://github.com/EYBlockchain/nightfall_3/issues/307#issuecomment-974616759) here.

I think the problem is when `proposersPrevious` === `proposersCurrent` which occurs when you add the second proposer.

The ordering of the `setProposer` calls results in an overwrite that causes `nextAddress` to have unexpected results

<img width="790" alt="Screen Shot 2021-11-20 at 19 03 47" src="https://user-images.githubusercontent.com/9293647/142723974-09b33961-6952-4213-9ca8-6b344ee0e55d.png">
