### ISSUE TITLE
Instant withdraw doesn't work when a transfer to a different account and a withdraw are part of the same L2 block

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#360]
Instant withdraw doesn't work when a transfer to a different account (not one's account) and a withdraw are part of the same L2 block. nighfall client cannot find withdraw hash. However, withdraw is executed (funds are not in ones account anymore).

**Comment by daveroga** [comment]
I have reproduced it in a test in a specific branch `daveroga/test-bug-instant-withdraw`.
You can run `./start-nightfall -g -s` and then `npm run test-e2e` and it will fail in test `test bug: should allow instant withdraw of existing withdraw`.

The test `test bug: should allow instant withdraw of existing withdraw` do:
- 2 deposits that mine a L2 block.
- 1 transfer from address1 to address2 and then 1 withdraw that mine another L2 block.
- 1 request withdraw that generates 1 instant witdraw by the liquidity provider and this generates the error.

This is happening when doing the transfer to a differnet address than the sender. I you try to change `nf3User2.ethereumAddress` by `nf3User1.ethereumAddress` in line 452 of the test and restart ganache and try to run again the test the issue is not happening.
