### ISSUE TITLE
Bridge Page

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#558]
The bridge page enables a user to move funds between Nightfall and Mainnet (deposit / withdraw). See sections 7 to 10 of the [HackMd](https://hackmd.io/@p4-pRlreS4a4NpxTZYUcMA/BJa1ntceq#7-Bridge-component) for more visuals.

The completion of tasks will be based on corresponding PRs.

## UI changes
- [x] Update UI/UX based on figma
- [x] Dropdown for token selection in deposit and withdraw
- [x] Max button clickable

## Feature changes
- [x] Ensure contract address for operation is based on dropdown option selected.
- [x] Current balance calculation on-screen
- [x] Show only 4 decimals
- [x] Enable spend All (if Max is clicked)
- [x] Check hyperlinks in left half (information panel)
- [x] Exception handling (e.g. withdrawal does not have the correct commitments available, depositing more than balance.)

**Comment by luizoamorim** [comment]
vcsdf

**Comment by luizoamorim** [comment]
![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/43e5c59b-2c72-4acd-85e7-f0010564ca1b)

Updated the styles to follow the last ui/ux passed for us in the figma document: https://www.figma.com/file/wpH5sn90CARgFCSWiSGRzh/Web-wallet-2.1?node-id=1298%3A4453

**Comment by luizoamorim** [comment]
### Got a polygon tokens list json to use like example to start the dropdown.

https://github.com/maticnetwork/polygon-token-list

**Comment by luizoamorim** [comment]
### Dropdown for token selection in deposit and withdraw

![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/5056b104-77e7-4ecf-a649-8eae8ada4921)

commit 5b7e6e14305293987fe87a9603c275d9d7b25f9a

**Comment by luizoamorim** [comment]
### scss responsive for large and medium screens

![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/7bffcb42-d320-4c0e-acef-b79213ebe889)

**Comment by luizoamorim** [comment]
## Updating balances, get contract address from token selected and enabling the MAX buttons for spend all

0b561cf8b0379dcbfe1a1a034ad7b3613087f3a5

**Comment by luizoamorim** [comment]
## Some questions

### Current balance calculation on-screen
@IlyasRidhuan I'm trying to understand better this requisite.

### Balance rounding
What is the better way for round the balances?

**Comment by luizoamorim** [comment]
## Next task to finish Current balance calculation on-screen

[ ] - Filter the pkds from getWalletBalance() and after filter by token address.

**Comment by luizoamorim** [comment]
### Removed the links because we're not using now
![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/0ef6f0bf-de38-46d6-9de1-b20225d11a7d)

### Input validation for withdraw
![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/1c01ed6d-b1b8-43b1-91b0-1f0b51b9421c)

### Input validation for deposit
![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/02a4d2a6-99f8-4f20-a0a5-2fcea57ad09a)

**Comment by luizoamorim** [comment]
### Exception handling (e.g. withdrawal does not have the correct commitments available, depositing more than balance.)

I think for withdraw is done alse, because we're getting all the commitments for the user in the Token selected and adding all values. So if the input is greater than this, the input is greater than all the commitments.

@IlyasRidhuan

**Comment by luizoamorim** [comment]
### Last commit
214f45e3801bf23a7ece0dfce0c67d2cc8139136

**Comment by luizoamorim** [comment]
@IlyasRidhuan if you could test this branch and see if the transfers are working fine, please.

luizoamorim/558-bridge-page

**Comment by luizoamorim** [comment]
### Fixing the l2 balance show

a8187dbde07c146ccd12ad5318e540086be3e672
