### ISSUE TITLE
create withdraw equivalent of double_transfer

### ISSUE THREAD

**Issue by Westlad** [EYBlockchain/nightfall_3#674]
At the moment a user can only withdraw an existing commitment back to Layer 1.  If they attempt to withdraw an amount for which there is no corresponding commitment, the withdraw will fail.  A user may not realise this and it will make them sad. The problem could be fixed by adding a circuit which enables a withdraw to consume two input commitments, and return the remaining value as a change commitment, just like a double_transfer does for transfers.

**Comment by IlyasRidhuan** [comment]
I think this is a solid step towards improving the flexibility and usability. Can this be easily generalised to other transactions (i.e. deposits and transfers)? If we were to do this I think it would make nightfall much more "complete" in the sense of a platform for private value transfer.

Since our transactions are structured to have fix lengths of commitments and nullifiers (2 & 2) I believe we can make it such that we support all combinations of these input/outputs.

Something like the following (I'll use the notation of `x -> y` to denote **x inputs to y outputs** or **x nullifiers used and y commitments created**)

- Deposits: `0 -> 1` (what we have now) or `0 -> 2` (not sure how useful this would be though)
- Transfers: `1 -> 1`, `2 -> 2`, (what we have now),  `2 -> 1`, `1 -> 2`
- Withdraw: `1 -> 0` (what we have now), `2 -> 0` (as suggested by this issue).

From a circuits perspective this should not be too difficult, Zokrates support for [generics](https://zokrates.github.io/language/generics.html) also means that we should be able to create reusable components for each of these transaction types.

I believe the greater complexity may come at the `contracts` stage. Currently, we use rigid definitions of `DEPOSIT, SINGLE_TRANSFER, DOUBLE_TRANSFER, WITHDRAW` and so we would need to think of a different way to handle the more generic versions I'm proposing above.

**Comment by ChaitanyaKonda** [comment]
Merging this issue into #525 and closing this
