### ISSUE TITLE
Multiple emitters from nf3 only receiving msg in one emitter

### ISSUE THREAD

**Issue by daveroga** [EYBlockchain/nightfall_3#801]
Defining different emitters for a nf3 instance is not working because only receiving messages in one of the emitters.

**Comment by imagobea** [comment]
I know that there are different emitters in place, but just a reminder that `getNewBlockEmitter` and `getChallengeEmitter` methods were removed from legacy `nf3` and will not be present in new SDK. I would suggest to elaborate the description a bit more, explaining e.g. where are these emitter, etc.

**Comment by daveroga** [comment]
I think these emitters will be in the SDK at least when proposer, challenger and liquidity provider will be integrated with the SDK as they provide information in some cases not being that role. A proposer might want to know if a challenge has been detected to one of their blocks.
Even from the point of a user might want to know when blocks are proposed to see if his transaction has been included in a block.

**Comment by imagobea** [comment]
I'm not suggesting that we shouldn't have emitters in the SDK, I am just pointing out that you and I decided to deprecate the methods I mentioned above a while ago because they were not in use (the old code suggests, for example, that `startProposer` may include the logic in `getNewBlockEmitter` hence why is not used). I just try to keep an eye on modifications to `nf3` so that we all are in the same page.
