### ISSUE TITLE
Analyzing NF for bottlenecks (TPS)

### ISSUE THREAD

**Issue by signorecello** [EYBlockchain/nightfall_3#925]
We need to run Nightfall with a large number of transactions and see which service needs to be refactored for TPS

**Comment by israelboudoux** [comment]
Current existing endpoints in **nightfall-client**:
```
/deposit
/contract-address
/transfer
/withdraw
/finalise-withdrawal
/valid-withdrawal
/commitment
/incoming-viewing-key
/set-instant-withdrawal
/generate-zkp-keys
```

**Comment by israelboudoux** [comment]
After talking with @signorecello, we agreed that at this stage only the `/transfer` endpoint will be tested, because it is likely that this endpoint will be the most used by the customer in case.

**Comment by israelboudoux** [comment]
The idea is to test components/endpoints used directly by the target endpoint. Follows the case for the `transfer` endpoint:
- /transfer
-- /worker/generate-proof
-- Shield.submitTransaction

After having the initial results I'll try to profile the node js app to have a better understanding of where are the bottlenecks.

**Comment by israelboudoux** [comment]
It was suggested that the TPS test was initially performed on the _inner_ parts, by _inner_ it should be understood testing directly the **Optimist** and the **Proposer** applications.

**Comment by israelboudoux** [comment]
It was suggested that the TPS test was initially performed on the _inner_ parts, by _inner_ it should be understood testing directly the **Optimist** and the **Proposer** applications.

**Comment by israelboudoux** [comment]
The first approach taken initially was to insert a big load of transactions directly into the Optimist's database, with the **Proposer** application stopped at the moment, and after finishing the import to the DB, then start the **Proposer** so that it could begin the processing.

I was able to generate **five million** transactions, but all of them were generated locally, and most of them were duplicated because it isn't possible to generate the correct transaction structure without spinning up the **nightfall-client** app. Generating such data load with with unique transactions using this approach was unpracticable since the client was taking _~10s_ for generating a transaction, even using many processes at once it didn't take effect.

**Comment by israelboudoux** [comment]
After starting the processing using the import approach, some issues popped up, sometimes the Optimist application crashed, and other times it was the Proposer's turn. I didn't understand why they were crashing, since the transaction structure is correct, despite the data not being consistent with the blockchain's current state on AWS stack.

The applications kept crashing continually and I wasn't able to keep going with the test using this approach. A good point is that these errors in the apps were discovered so that we can take an action on them.

**Action to take**: Patch the **Optimist and Proposer applications** so that they work resiliently without crashing in face of unexpected errors.

**Comment by israelboudoux** [comment]
I had to give up on that _import_ approach since it didn't work. I would have to go to another, that despite being much slower, would allow me to test the Transactions per Second on the inner parts. Follows the idea:
- Spin up the **Optimist application** (AWS);
- Stop the **Proposer application** (AWS);
- Spin up a **nightfall-client** application locally;
- Start a process to call the nightfall-client app to generate enough transactions;
- Start the Proposer app;
- Measure the processing time when all the transactions get processed.

**Comment by israelboudoux** [comment]
It took approximately three days for generating _~6.5k_ transactions. Unfortunately, (I guess) the testing data generated can be used only once, since the state of the blockchain application will be different for each run, even if we reset it.

Here goes the result:
- **Environment used:** staging
- **Optimist hardware configuration:** 1 vCPU / 2 GB
- **Proposer hardware configuration:** .25 vCPU / .5 GB
- **Total transactions:** 6747
- **TRANSACTIONS PER SECOND** ¹: ~53
- **TRANSACTIONS PER SECOND** ²: ~2.4

**Comment by israelboudoux** [comment]
### Optimist's Report

For the Optimist the report highlighted a good deal of performance improvements. Some can be seen in the attached log file. Follows the list with the ones with the biggest processing times:
```
  32.06%     0.00%  node      [JIT] tid 28          [.] Function:^verifyProof file:///app/src/services/transaction-checker.mjs:122                                                                                                                                                                                                                                                       
  23.50%    13.09%  node      [JIT] tid 28          [.] LazyCompile:*convertBase /app/node_modules/zkp-utils/number-conversions/convert-base.js:63                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  21.41%     0.00%  node      [JIT] tid 28          [.] Function:^VerificationKey file:///app/src/classes/verification-key.mjs:16                                                                                                                                                                                                                                                        
  19.17%     0.02%  node      [JIT] tid 28          [.] LazyCompile:*FixedBytesCoder.encode /app/node_modules/@ethersproject/abi/lib/coders/fixed-bytes.js:34                                                                                                                                                                                                                            
  16.56%     0.00%  node      [JIT] tid 28          [.] Function:^waitForContract file:///app/src/event-handlers/subscribe.mjs:61                                                                                                                                                                                                                                                        
  16.52%     0.00%  node      [JIT] tid 28          [.] Function:^getContractInterface file:///app/node_modules/common-files/utils/contract.mjs:18    
  10.05%     0.15%  node      [JIT] tid 28          [.] LazyCompile:*poseidonHash file:///app/node_modules/common-files/utils/crypto/poseidon/poseidon.mjs:40                                                                                                                                                                                                                            
   9.03%     0.00%  node      [JIT] tid 28          [.] Function:^getContractInstance file:///app/node_modules/common-files/utils/contract.mjs:44                                                                                                                                                                                                                                        
   8.73%     0.00%  node      [JIT] tid 28          [.] LazyCompile:*Module._nodeModulePaths node:internal/modules/cjs/loader:640                                                                                                                                                                                                                                                        
   8.40%     0.00%  node      [JIT] tid 28          [.] Function:^statelessUpdate file:///app/node_modules/common-files/classes/timber.mjs:528                                                                                                                                                                                                                                           
   7.56%     0.01%  node      [JIT] tid 28          [.] LazyCompile:*reduceTree file:///app/node_modules/common-files/classes/timber.mjs:314                                                                                                                                                                                                                                             
   7.56%     0.00%  node      [JIT] tid 28          [.] Function:^hashTree file:///app/node_modules/common-files/classes/timber.mjs:335                                                                                                                                                                                                                                                 
   6.94%     6.06%  node      [JIT] tid 28          [.] LazyCompile:*multiplyByNumber /app/node_modules/zkp-utils/number-conversions/convert-base.js:39                                                                                                                                                                                                                                  
   6.44%     0.00%  node      [JIT] tid 28          [.] Function:^insertLeaves file:///app/node_modules/common-files/classes/timber.mjs:481 
```

Following the suggestion for the Proposer app, we can take advantage of data caching for the following functions since they are shown in the report file, in the `[Bottom up (heavy) profile]` section, that they are the calls with more hits:
- **getContractAddress**;
- **getContractInterface**; and
- **getContractInstance**.

[https://app.zenhub.com/files/362741913/4d635b76-1951-4487-85e7-c3f0a0417406/download](https://app.zenhub.com/files/362741913/4d635b76-1951-4487-85e7-c3f0a0417406/download)

**Comment by israelboudoux** [comment]
### How can we improve the performance of the parts (Optimist & Proposer)?

**Beyond the reported bottlenecks found, scaling the applications horizontally would be a solution.**

**- Are the apps currently able to be horizontally scaled up?**
No, the Optimist codbase would need to be refactored to avoid collision when selecting transactions in the DB; and the way the Proposer receives notification would need to be changed.

### - Proposals:
### 1. Merge both apps into just one
- Pros:
	- No need to manage connections optimist <-> proposer
	- Simplified deployment
	- Error handling simplified
	- Scale simplified - no need to put a reource in front of Proposer apps to manage WS connections
- Cons:
	- We would have to refactor and rebuild (I honestly don't think this is a _con_)

### 2. Refactor the apps to scale properly
- Pros:
	- Use of the same code base with some sort of refactoring to allow horizontal scalability
- Cons:
	- As the WS connection is 1-1 it would require an additional resource to put between Optimist & Proposer to avoid tight a 1-1 conn;
	- We still can loose the connection with the Proposers.

**Comment by druiz0992** [comment]
Transaction/block processing is done in three stages:
- `transaction submitted` in nightfall-optimist/src/event-handlers/transacction-submitted.mjs
- `block assembly` in nightfall-optimist/src/services/block-assembler.mjs
- `block proposed` in nightfall-optimist/sec/event-handlers/block-proposed.mjs

**Comment by israelboudoux** [comment]
Here are some graphs for the main events in the Optimist:
- Block Proposed - https://docs.google.com/spreadsheets/d/1Lrtgb7cUjZLUNf13xzhKZ02FHVyh8c9unKyUNLU1eos/edit?usp=sharing
- New Blocks - https://docs.google.com/spreadsheets/d/1VHrFasBDQoEw8GX4x8j3r65hULzrYT0QbnRC39ot0GM/edit?usp=sharing
- Transaction Submmited - https://docs.google.com/spreadsheets/d/1FVUYWkWFJ0UgmQi1l4wnO1z8u7jbaNoEyZXeb1ncZKo/edit?usp=sharing

**Comment by israelboudoux** [comment]
Following are the results of the load test for the `nightfall-client` application. The tests were run only on the `deposit`, `transfer` and `withdraw` endpoints.

The tool used was **Apache Bench**, a very simple and fast tool for running load tests.

Results for `Deposit` endpoint:
```
Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /deposit
Document Length:        3779 bytes

Concurrency Level:      10
Time taken for tests:   425.651 seconds
Complete requests:      10000
Failed requests:        0
Keep-Alive requests:    10000
Total transferred:      40820000 bytes
Total body sent:        4940000
HTML transferred:       37790000 bytes
Requests per second:    23.49 [#/sec] (mean)
Time per request:       425.651 [ms] (mean)
Time per request:       42.565 [ms] (mean, across all concurrent requests)
Transfer rate:          93.65 [Kbytes/sec] received
                        11.33 kb/s sent
                        104.99 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:   285  425  74.3    409     887
Waiting:      285  425  74.3    408     887
Total:        285  425  74.3    409     887

Percentage of the requests served within a certain time (ms)
  50%    409
  66%    442
  75%    469
  80%    489
  90%    534
  95%    565
  98%    604
  99%    632
 100%    887 (longest request)
```

Results for `Transfer` endpoint:
```
Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /transfer
Document Length:        3779 bytes

Concurrency Level:      10
Time taken for tests:   1908.795 seconds
Complete requests:      77
Failed requests:        0
Keep-Alive requests:    77
Total transferred:      314314 bytes
Total body sent:        46197
HTML transferred:       290983 bytes
Requests per second:    0.04 [#/sec] (mean)
Time per request:       247895.476 [ms] (mean)
Time per request:       24789.548 [ms] (mean, across all concurrent requests)
Transfer rate:          0.16 [Kbytes/sec] received
                        0.02 kb/s sent
                        0.18 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing: 45978 226839 43504.1 238719  262693
Waiting:    45978 226839 43504.1 238719  262693
Total:      45978 226839 43504.1 238719  262693

Percentage of the requests served within a certain time (ms)
  50%  238670
  66%  241595
  75%  242937
  80%  243513
  90%  247361
  95%  247865
  98%  248080
  99%  262693
 100%  262693 (longest request)
```

Results for `Withdraw` endpoint:
```
Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /withdraw
Document Length:        3779 bytes

Concurrency Level:      10
Time taken for tests:   828.021 seconds
Complete requests:      35
Failed requests:        0
Keep-Alive requests:    35
Total transferred:      142870 bytes
Total body sent:        21420
HTML transferred:       132265 bytes
Requests per second:    0.04 [#/sec] (mean)
Time per request:       236577.510 [ms] (mean)
Time per request:       23657.751 [ms] (mean, across all concurrent requests)
Transfer rate:          0.17 [Kbytes/sec] received
                        0.03 kb/s sent
                        0.19 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing: 29159 195953 58397.7 223890  244555
Waiting:    29159 195953 58397.7 223890  244555
Total:      29159 195953 58397.7 223890  244555

Percentage of the requests served within a certain time (ms)
  50%  223777
  66%  224923
  75%  225441
  80%  225700
  90%  228223
  95%  230483
  98%  244555
  99%  244555
 100%  244555 (longest request)
```

As one can see, the tests were run on `localhost`. The idea was to run them on a dedicated server too, but the results wouldn't change much for `Transfer` and `Withdraw`. The main reason for these results to be so poor for the mentioned services is that the _proof generation_ takes a good while for processing.

Suggestion:
As far as I know, a work is being conducted towards improving the circuits for these operations and soon they will be much faster than today, however the flow should be reviewed.

**Comment by imagobea** [comment]
Hello @israelboudoux 
Thank you for this. Very insightful.
I left an emoji :eyes: , because I am not sure the links to the "graphs" point at the correct docs.

Some "app crashes" are due to bad handled promises. Basically promises that are not "awaited" - potentially for "speeding up" processes - that do not capture exceptions either (this we recently confirmed with @daveroga ).

Also, for many cases when an error happens there's no plan B beyond logging. We should tackle these cases too.

Thanks again.
